### ISSUE TITLE
为什么我按照你的步骤操作以后控制台总是在p站那一行报错？

### ISSUE THREAD

**Issue by humidityorder** [BlockyDeer/CaddyConfig#1]
![image](https://github.com/user-attachments/assets/e35992cb-c7dc-492d-8a37-6fdfe7bfac98)
大概就是这样，而且无限循环

**Comment by humidityorder** [comment]
我使用的是steamcommunity302 12.1.45 caddy用的是文章中提到的2.9.2，最新版本的caddy是这样的
![image](https://github.com/user-attachments/assets/d3ac7995-f255-4058-8f8e-de2fdfe249de)

**Comment by BlockyDeer** [comment]
请发全部详细的日志，谢谢

**Comment by humidityorder** [comment]
我找不到运行日志存放在哪，控制台也不停地在输出，两个多小时了还在输出，我就直接关闭了控制台

**Comment by humidityorder** [comment]
> 请发全部详细的日志，谢谢

我找不到运行日志存放在哪，控制台也不停地在输出，两个多小时了还在输出，我就直接关闭了控制台

**Comment by BlockyDeer** [comment]
只用这个能成功访问pixiv吗

**Comment by BlockyDeer** [comment]
我这边试验了一下，发现不行，那就是不行了，steamcommunity302的作者早已移除了pixiv支持，我这个仓库的意义就是给那个功能强行续命，不受作者支持的功能早晚坏掉。挂掉了我也没办法，我也没有学过caddy配置，这仓库只是作为分享。
